# Use postgres/example user/password credentials
version: '3.9'

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: password1
            POSTGRES_DB: goji_interview
            POSTGRES_USER: admin
        ports:
            - '5432:5432'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        environment:
            - REDIS_PORT=6379
        platform: linux/amd64

    api:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        ports:
            - '4000:4000'
        env_file:
            - ./api/.env
        volumes:
            - ./api:/usr/src/api
            - /usr/src/api/node_modules
        depends_on:
            - db
            - redis

    web:
        build:
            context: ./web
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        env_file:
            - ./web/.env
        volumes:
            - ./web:/usr/src/web
            - /usr/src/web/node_modules
        depends_on:
            - api
