FROM node:22

WORKDIR /usr/src/api

COPY package*.json ./

RUN npm ci

COPY . ./

RUN npm run prisma:generate:client
# RUN npm run prisma:migrate:deploy
# RUN npx prisma db seed

EXPOSE $PORT

CMD ["npm", "run", "start:dev"]
